.TH "android.support.v4.R" 3 "Wed Sep 9 2020" "Autosulivan's Feeder Android APP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
android.support.v4.R
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Definition at line 9 of file R\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autosulivan's Feeder Android APP from the source code\&.
