.TH "com" 3 "Wed Sep 9 2020" "Autosulivan's Feeder Android APP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com
.SH SYNOPSIS
.br
.PP
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBtorijano\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Autosulivan's Feeder Android APP from the source code\&.
