.TH "me.aflak.bluetoothterminal.Scan" 3 "Wed Sep 9 2020" "Autosulivan's Feeder Android APP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
me.aflak.bluetoothterminal.Scan
.SH SYNOPSIS
.br
.PP
.PP
Inherits Activity, DiscoveryCallback, and OnItemClickListener\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBonFinish\fP ()"
.br
.ti -1c
.RI "void \fBonDevice\fP (final BluetoothDevice device)"
.br
.ti -1c
.RI "void \fBonPair\fP (BluetoothDevice device)"
.br
.ti -1c
.RI "void \fBonUnpair\fP (BluetoothDevice device)"
.br
.ti -1c
.RI "void \fBonError\fP (String message)"
.br
.ti -1c
.RI "void \fBonItemClick\fP (AdapterView<?> parent, View view, int position, long id)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBonCreate\fP (Bundle savedInstanceState)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file Scan\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void me\&.aflak\&.bluetoothterminal\&.Scan\&.onCreate (Bundle savedInstanceState)\fC [protected]\fP"

.PP
Definition at line 30 of file Scan\&.java\&.
.SS "void me\&.aflak\&.bluetoothterminal\&.Scan\&.onDevice (final BluetoothDevice device)"

.PP
Definition at line 105 of file Scan\&.java\&.
.SS "void me\&.aflak\&.bluetoothterminal\&.Scan\&.onError (String message)"

.PP
Definition at line 133 of file Scan\&.java\&.
.SS "void me\&.aflak\&.bluetoothterminal\&.Scan\&.onFinish ()"

.PP
Definition at line 92 of file Scan\&.java\&.
.SS "void me\&.aflak\&.bluetoothterminal\&.Scan\&.onItemClick (AdapterView<?> parent, View view, int position, long id)"

.PP
Definition at line 139 of file Scan\&.java\&.
.SS "void me\&.aflak\&.bluetoothterminal\&.Scan\&.onPair (BluetoothDevice device)"

.PP
Definition at line 118 of file Scan\&.java\&.
.SS "void me\&.aflak\&.bluetoothterminal\&.Scan\&.onUnpair (BluetoothDevice device)"

.PP
Definition at line 127 of file Scan\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autosulivan's Feeder Android APP from the source code\&.
