.TH "me.aflak.bluetoothterminal.BuildConfig" 3 "Wed Sep 9 2020" "Autosulivan's Feeder Android APP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
me.aflak.bluetoothterminal.BuildConfig
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final boolean \fBDEBUG\fP = Boolean\&.parseBoolean('true')"
.br
.ti -1c
.RI "static final String \fBAPPLICATION_ID\fP = 'com\&.torijano\&.autosulivansFeeder'"
.br
.ti -1c
.RI "static final String \fBBUILD_TYPE\fP = 'debug'"
.br
.ti -1c
.RI "static final String \fBFLAVOR\fP = ''"
.br
.ti -1c
.RI "static final int \fBVERSION_CODE\fP = 1"
.br
.ti -1c
.RI "static final String \fBVERSION_NAME\fP = '3\&.5'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file BuildConfig\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final String me\&.aflak\&.bluetoothterminal\&.BuildConfig\&.APPLICATION_ID = 'com\&.torijano\&.autosulivansFeeder'\fC [static]\fP"

.PP
Definition at line 8 of file BuildConfig\&.java\&.
.SS "final String me\&.aflak\&.bluetoothterminal\&.BuildConfig\&.BUILD_TYPE = 'debug'\fC [static]\fP"

.PP
Definition at line 9 of file BuildConfig\&.java\&.
.SS "final boolean me\&.aflak\&.bluetoothterminal\&.BuildConfig\&.DEBUG = Boolean\&.parseBoolean('true')\fC [static]\fP"

.PP
Definition at line 7 of file BuildConfig\&.java\&.
.SS "final String me\&.aflak\&.bluetoothterminal\&.BuildConfig\&.FLAVOR = ''\fC [static]\fP"

.PP
Definition at line 10 of file BuildConfig\&.java\&.
.SS "final int me\&.aflak\&.bluetoothterminal\&.BuildConfig\&.VERSION_CODE = 1\fC [static]\fP"

.PP
Definition at line 11 of file BuildConfig\&.java\&.
.SS "final String me\&.aflak\&.bluetoothterminal\&.BuildConfig\&.VERSION_NAME = '3\&.5'\fC [static]\fP"

.PP
Definition at line 12 of file BuildConfig\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autosulivan's Feeder Android APP from the source code\&.
