.TH "me.aflak.bluetoothterminal.Select" 3 "Wed Sep 9 2020" "Autosulivan's Feeder Android APP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
me.aflak.bluetoothterminal.Select
.SH SYNOPSIS
.br
.PP
.PP
Inherits Activity, and OnRefreshListener\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBonRefresh\fP ()"
.br
.ti -1c
.RI "void \fBonDestroy\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBonCreate\fP (Bundle savedInstanceState)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Created by Omar on 16/07/2015\&. 
.PP
Definition at line 27 of file Select\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void me\&.aflak\&.bluetoothterminal\&.Select\&.onCreate (Bundle savedInstanceState)\fC [protected]\fP"

.PP
Definition at line 36 of file Select\&.java\&.
.SS "void me\&.aflak\&.bluetoothterminal\&.Select\&.onDestroy ()"

.PP
Definition at line 109 of file Select\&.java\&.
.SS "void me\&.aflak\&.bluetoothterminal\&.Select\&.onRefresh ()"

.PP
Definition at line 87 of file Select\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autosulivan's Feeder Android APP from the source code\&.
