.TH "me.aflak.bluetoothterminal.Chat" 3 "Wed Sep 9 2020" "Autosulivan's Feeder Android APP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
me.aflak.bluetoothterminal.Chat
.SH SYNOPSIS
.br
.PP
.PP
Inherits AppCompatActivity, CommunicationCallback, and OnDateSetListener\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBonBackPressed\fP ()"
.br
.ti -1c
.RI "void \fBonDestroy\fP ()"
.br
.ti -1c
.RI "boolean \fBonCreateOptionsMenu\fP (Menu menu)"
.br
.ti -1c
.RI "boolean \fBonOptionsItemSelected\fP (MenuItem item)"
.br
.ti -1c
.RI "void \fBDisplay\fP (final String s)"
.br
.ti -1c
.RI "void \fBonConnect\fP (BluetoothDevice device)"
.br
.ti -1c
.RI "void \fBfijarPeso\fP ()"
.br
.ti -1c
.RI "void \fBonDisconnect\fP (BluetoothDevice device, String message)"
.br
.ti -1c
.RI "void \fBonMessage\fP (String message)"
.br
.ti -1c
.RI "void \fBonError\fP (String message)"
.br
.ti -1c
.RI "void \fBonConnectError\fP (final BluetoothDevice device, String message)"
.br
.ti -1c
.RI "void \fBonDateSet\fP (DatePicker datePicker, int i, int i1, int i2)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static final void \fBhideKeyboard\fP (Activity activity)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "final Calendar \fBc\fP = Calendar\&.getInstance()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBonCreate\fP (Bundle savedInstanceState)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 51 of file Chat\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void me\&.aflak\&.bluetoothterminal\&.Chat\&.Display (final String s)"

.PP
Definition at line 381 of file Chat\&.java\&.
.SS "void me\&.aflak\&.bluetoothterminal\&.Chat\&.fijarPeso ()"

.PP
Definition at line 429 of file Chat\&.java\&.
.SS "static final void me\&.aflak\&.bluetoothterminal\&.Chat\&.hideKeyboard (Activity activity)\fC [static]\fP"

.PP
Definition at line 77 of file Chat\&.java\&.
.SS "void me\&.aflak\&.bluetoothterminal\&.Chat\&.onBackPressed ()"

.PP
Definition at line 89 of file Chat\&.java\&.
.SS "void me\&.aflak\&.bluetoothterminal\&.Chat\&.onConnect (BluetoothDevice device)"

.PP
Definition at line 407 of file Chat\&.java\&.
.SS "void me\&.aflak\&.bluetoothterminal\&.Chat\&.onConnectError (final BluetoothDevice device, String message)"

.PP
Definition at line 476 of file Chat\&.java\&.
.SS "void me\&.aflak\&.bluetoothterminal\&.Chat\&.onCreate (Bundle savedInstanceState)\fC [protected]\fP"

.PP
Definition at line 100 of file Chat\&.java\&.
.SS "boolean me\&.aflak\&.bluetoothterminal\&.Chat\&.onCreateOptionsMenu (Menu menu)"

.PP
Definition at line 323 of file Chat\&.java\&.
.SS "void me\&.aflak\&.bluetoothterminal\&.Chat\&.onDateSet (DatePicker datePicker, int i, int i1, int i2)"

.PP
Definition at line 525 of file Chat\&.java\&.
.SS "void me\&.aflak\&.bluetoothterminal\&.Chat\&.onDestroy ()"

.PP
Definition at line 274 of file Chat\&.java\&.
.SS "void me\&.aflak\&.bluetoothterminal\&.Chat\&.onDisconnect (BluetoothDevice device, String message)"

.PP
Definition at line 434 of file Chat\&.java\&.
.SS "void me\&.aflak\&.bluetoothterminal\&.Chat\&.onError (String message)"

.PP
Definition at line 471 of file Chat\&.java\&.
.SS "void me\&.aflak\&.bluetoothterminal\&.Chat\&.onMessage (String message)"

.PP
Definition at line 457 of file Chat\&.java\&.
.SS "boolean me\&.aflak\&.bluetoothterminal\&.Chat\&.onOptionsItemSelected (MenuItem item)"

.PP
Definition at line 330 of file Chat\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final Calendar me\&.aflak\&.bluetoothterminal\&.Chat\&.c = Calendar\&.getInstance()"

.PP
Definition at line 69 of file Chat\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autosulivan's Feeder Android APP from the source code\&.
