.TH "E:/TFG/appAndroid/autosulivansFeederApp/app/build/generated/not_namespaced_r_class_sources/debug/r/me/aflak/pulltorefresh/R.java" 3 "Wed Sep 9 2020" "Autosulivan's Feeder Android APP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/TFG/appAndroid/autosulivansFeederApp/app/build/generated/not_namespaced_r_class_sources/debug/r/me/aflak/pulltorefresh/R.java
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBme\&.aflak\&.pulltorefresh\&.R\fP"
.br
.ti -1c
.RI "class \fBme\&.aflak\&.pulltorefresh\&.R\&.anim\fP"
.br
.ti -1c
.RI "class \fBme\&.aflak\&.pulltorefresh\&.R\&.attr\fP"
.br
.ti -1c
.RI "class \fBme\&.aflak\&.pulltorefresh\&.R\&.bool\fP"
.br
.ti -1c
.RI "class \fBme\&.aflak\&.pulltorefresh\&.R\&.color\fP"
.br
.ti -1c
.RI "class \fBme\&.aflak\&.pulltorefresh\&.R\&.dimen\fP"
.br
.ti -1c
.RI "class \fBme\&.aflak\&.pulltorefresh\&.R\&.drawable\fP"
.br
.ti -1c
.RI "class \fBme\&.aflak\&.pulltorefresh\&.R\&.id\fP"
.br
.ti -1c
.RI "class \fBme\&.aflak\&.pulltorefresh\&.R\&.integer\fP"
.br
.ti -1c
.RI "class \fBme\&.aflak\&.pulltorefresh\&.R\&.layout\fP"
.br
.ti -1c
.RI "class \fBme\&.aflak\&.pulltorefresh\&.R\&.string\fP"
.br
.ti -1c
.RI "class \fBme\&.aflak\&.pulltorefresh\&.R\&.style\fP"
.br
.ti -1c
.RI "class \fBme\&.aflak\&.pulltorefresh\&.R\&.styleable\fP"
.br
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBme\&.aflak\&.pulltorefresh\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Autosulivan's Feeder Android APP from the source code\&.
