.TH "C:/Users/The_menda14/Desktop/Nueva carpeta Directory Reference" 3 "Wed Sep 9 2020" "Autosulivan's Feeder Firmware" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/The_menda14/Desktop/Nueva carpeta Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAutoSulivan_sFeeder\&.cpp\fP"
.br
.in -1c
